import { Procedure, AppSettings } from './types';
import allProceduresJson from './data/allProcedures.json';

export const DEFAULT_APP_SETTINGS: AppSettings = {
  siteTitle: 'TTPVHCC XÃ BA CHẼ - CỔNG TRA CỨU THỦ TỤC HÀNH CHÍNH',
  siteSubtitle: 'Cổng thông tin điện tử nâng cao chỉ số cải cách hành chính, quản lý dữ liệu số hóa quy chuẩn quốc gia',
  logoEmoji: '🏛️',
  badgeLabel: 'DỮ LIỆU ĐỒNG BỘ',
  systemVersion: 'v2.6.4',
  footerMainText: '© 2026 Bản quyền thuộc Cổng thông tin điều chế & quản lý dữ liệu Thủ tục Hành chính.',
  footerSubText: 'Phục vụ công tác chuyển đổi số cấp cơ sở và nâng cao chỉ số cải cách hành chính (PAR INDEX).'
};

export const INITIAL_PROCEDURES: Procedure[] = allProceduresJson as Procedure[];

export const LINH_VUC_PRESETS = [
  'Lao động',
  'Phòng, chống tệ nạn xã hội',
  'An toàn thực phẩm',
  'Tín ngưỡng, tôn giáo',
  'Công tác dân tộc',
  'Quản lý nhà nước về hội, quỹ',
  'Quy hoạch đô thị và nông thôn',
  'Giáo dục tiểu học',
  'Hoạt động xây dựng',
  'Đường bộ',
  'Hải quan',
  'Hàng hải và đường thủy nội địa',
  'Nuôi con nuôi',
  'Chăn nuôi',
  'Hạ tầng kỹ thuật',
  'Nhà ở và công sở',
  'Thủy lợi',
  'Địa chất và khoáng sản',
  'Quản lý chất lượng công trình xây dựng',
  'Chứng thực',
  'Môi trường',
  'Hòa giải ở cơ sở',
  'Quản lý đê điều và phòng, chống thiên tai',
  'Thủy sản',
  'Lâm nghiệp và kiểm lâm',
  'Hộ tịch',
  'Trồng trọt',
  'Biển và hải đảo',
  'Đất đai',
  'Thú y',
  'Kinh tế hợp tác và phát triển nông thôn',
  'Giảm nghèo',
  'Trẻ em',
  'Bảo trợ xã hội',
  'Thi đua, khen thưởng',
  'Quản lý lao động ngoài nước',
  'Giáo dục và đào tạo thuộc hệ thống giáo dục quốc dân',
  'Giáo dục mầm non',
  'Giáo dục thường xuyên',
  'Giáo dục trung học',
  'Giáo dục nghề nghiệp (g07-lđ06)',
  'Bồi thường nhà nước',
  'Thi, tuyển sinh',
  'Tài nguyên nước',
  'Tài sản kết cấu hạ tầng chợ do nhà nước đầu tư, quản lý',
  'An toàn đập, hồ chứa thuỷ điện',
  'Người có công',
  'Bảo vệ quyền lợi người tiêu dùng',
  'Việc làm',
  'Phát thanh, truyền hình và thông tin điện tử',
  'Lao động, tiền lương',
  'Công chức, viên chức',
  'Di sản văn hóa',
  'Văn hóa',
  'Gia đình',
  'Thể dục thể thao',
  'Bảo hiểm xã hội',
  'Thành lập và hoạt động doanh nghiệp (hộ kinh doanh)',
  'Thành lập và hoạt động của tổ hợp tác, hợp tác xã, liên hiệp hợp tác xã',
  'Quản lý kết cấu hạ tầng giao thông',
  'Ứng phó sự cố tràn dầu bqp',
  'Đăng ký biện pháp bảo đảm',
  'Tài chính đất đai',
  'Đăng ký, quản lý cư trú',
  'Quản lý chương trình mục tiêu quốc gia',
  'Xuất bản, in và phát hành',
  'Nghĩa vụ quân sự',
  'Điện lực',
  'Quản lý thuế, phí, lệ phí và thu khác của ngân sách nhà nước',
  'Cụm công nghiệp',
  'Trồng trọt và bảo vệ thực vật'
];

export const SO_NGANH_PRESETS = [
  'Bộ Nội vụ',
  'Bộ Y tế',
  'Bộ Dân tộc và Tôn giáo',
  'Bộ Xây dựng',
  'Bộ Giáo dục và Đào tạo',
  'Bộ xây dựng (Giao thông vận tải cũ)',
  'Bộ Tài chính',
  'Bộ Tư pháp',
  'Bộ Nông nghiệp và Môi trường',
  'Bộ Công thương',
  'Bộ Văn hóa, Thể thao và Du lịch',
  'UBND tỉnh Quảng Ninh',
  'Bộ Quốc phòng',
  'Bộ Công an',
  'UBND cấp xã'
];

export const CAP_THUC_HIEN_PRESETS = [
  'Cấp xã',
  'Thành phố',
  'Cấp xã, Thành phố',
  'TTHC liên thông'
];
